// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRjj2E2bd0jbGc6H8MswHQH6u4CZu3ffw',
    appId: '1:257967119307:web:35f2ab9a60b4e80302f44e',
    messagingSenderId: '257967119307',
    projectId: 'same-102e7',
    authDomain: 'same-102e7.firebaseapp.com',
    storageBucket: 'same-102e7.appspot.com',
    measurementId: 'G-DXL337Y7LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxWPqcNHJYhuda5DYM5H4nbaoF4YCq3g',
    appId: '1:257967119307:android:d06d0d48fa092c2502f44e',
    messagingSenderId: '257967119307',
    projectId: 'same-102e7',
    storageBucket: 'same-102e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT6LaolC009Ldu-jivFyH6OOKWqvh2bTI',
    appId: '1:257967119307:ios:0401d1fb50f2e61f02f44e',
    messagingSenderId: '257967119307',
    projectId: 'same-102e7',
    storageBucket: 'same-102e7.appspot.com',
    iosBundleId: 'com.example.same',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT6LaolC009Ldu-jivFyH6OOKWqvh2bTI',
    appId: '1:257967119307:ios:8c19eae5a005571702f44e',
    messagingSenderId: '257967119307',
    projectId: 'same-102e7',
    storageBucket: 'same-102e7.appspot.com',
    iosBundleId: 'com.example.same.RunnerTests',
  );
}
